### ISSUE TITLE
I think this is how this works

### ISSUE THREAD

**Issue by Brettem** [liebecon/astr302-liebecon#1]
Are we supposed to just make those lines separate in markdown?

**Comment by liebecon** [comment]
I have no idea. Pretty sure we are just suppose to "fix" something

**Comment by liebecon** [comment]
Like I have an accidental typo in my message if you want to fix it

**Comment by Brettem** [comment]
Oh perfect

**Comment by liebecon** [comment]
Yah kinda worked out so have at it

**Comment by Brettem** [comment]
There we go I think I started pull request for it now.

**Comment by liebecon** [comment]
I merged it nice job!

**Comment by liebecon** [comment]
It worked btw
